[package]
name = "kitlogger-sampling"
version = "0.1.0"
edition = "2021"

[dependencies]
kitlogger-log-domain = { path = "../kitlogger-log-domain" }
kit-config = { path = "../../../kit-config/crates/kit-config", default-features = false, features = ["logging"] }
fastrand = "2"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
