[package]
name = "file-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
kit-config = { git = "https://github.com/pablogore/kit-config.git", branch = "master", default-features = false, features = ["logging"] }
kitlogger-log-domain = { path = "../kitlogger-log-domain" }
output-adapter-contracts = { path = "../output-adapter-contracts" }

[dev-dependencies]
tempfile = "3"
