[package]
name = "kitlogger"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
console-exporter = { path = "../console-exporter" }
telemetry-adapter-contracts = { path = "../telemetry-adapter-contracts" }
telemetry-types = { path = "../telemetry-types" }
kitlogger-log-domain = { path = "../kitlogger-log-domain" }