[package]
name = "kitlogger"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
console-exporter = { path = "../console-exporter" }
telemetry-adapter-contracts = { path = "../telemetry-adapter-contracts" }
telemetry-types = { path = "../telemetry-types" }
telemetry-config-semantics = { path = "../telemetry-config-semantics" }
kitlogger-log-domain = { path = "../kitlogger-log-domain" }
kitlogger-formatter = { path = "../kitlogger-formatter" }
kitlogger-sampling = { path = "../kitlogger-sampling" }
kitlogger-redaction = { path = "../kitlogger-redaction" }
output-adapter-contracts = { path = "../output-adapter-contracts" }
file-exporter = { path = "../file-exporter" }
kit-config = { path = "../../../kit-config/crates/kit-config", default-features = false, features = ["logging"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }